# # Smart pane switching with awareness of Vim splits.
# # See: https://github.com/christoomey/vim-tmux-navigator
# vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
# is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
#     | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
# bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
# bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
# bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
# bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'


# bind-key -n C-h if-shell -F "#{pane_at_left}" "run-shell \"aerospace focus left\"" "select-pane -R"
# bind-key -n C-j if-shell -F "#{pane_at_bottom}" "run-shell \"aerospace focus down\"" "select-pane -R"
# bind-key -n C-k if-shell -F "#{pane_at_top}" "run-shell \"aerospace focus up\"" "select-pane -R"
# bind-key -n C-l if-shell -F "#{pane_at_right}" "run-shell \"aerospace focus right\"" "select-pane -R"

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind -T copy-mode-vi 'C-h' select-pane -L
bind -T copy-mode-vi 'C-j' select-pane -D
bind -T copy-mode-vi 'C-k' select-pane -U
bind -T copy-mode-vi 'C-l' select-pane -R
bind -T copy-mode-vi 'C-\' select-pane -l

set-option -g prefix C-Space
unbind C-b
set -a terminal-features "kitty-256color:RGB"
set -g mouse 'on'
set -g status-position top
set -g status-bg "#000000"
set -g base-index 1
set -g pane-base-index 1

bind -n 'C-\' last-window

bind r 'source ~/.config/tmux/tmux.conf'
bind p 'popup -BE -w 80% -h 80% tmux kill-pane'
bind g 'run-shell "open 'https://github.com/$(pbpaste)'"'
bind C-Space 'run-shell ~/.config/tmux/seshy.sh'
bind C-h split-window -hb
bind C-j split-window
bind C-k split-window -b
bind C-l split-window -h

source "$HOME/.config/tmux/colorscheme.conf"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style "bg=default"
set -g status-left '#[fg=#989898,bold]#S'
set -g status-right '#(~/.config/tmux/battery.sh)#[fg=#989898] %H:%M'
set -g window-status-current-style 'fg=#fab387,bold'
set -g window-status-style '#{?window_last_flag,fg=#89dceb,fg=#d4d4d4}'
set -g window-status-format '#I.#W'
set -g window-status-current-format '#I.#W'
set -g window-status-separator ' '
set -g status-left-length 100
set -g status-right-length 100
set -g status-justify centre
